-- MySQL Script generated by MySQL Workbench
-- Sat Nov 18 13:26:44 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbsimples
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbsimples` ;

-- -----------------------------------------------------
-- Schema dbsimples
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbsimples` DEFAULT CHARACTER SET utf8 ;
USE `dbsimples` ;

-- -----------------------------------------------------
-- Table `dbsimples`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbsimples`.`endereco` ;

CREATE TABLE IF NOT EXISTS `dbsimples`.`endereco` (
  `cep` VARCHAR(15) NOT NULL,
  `uf` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cep`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsimples`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbsimples`.`cliente` ;

CREATE TABLE IF NOT EXISTS `dbsimples`.`cliente` (
  `cpf` VARCHAR(15) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(14) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `endereco_cep` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`cpf`),
  INDEX `endereco_cliente_idx` (`endereco_cep` ASC),
  CONSTRAINT `endereco_cliente`
    FOREIGN KEY (`endereco_cep`)
    REFERENCES `dbsimples`.`endereco` (`cep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsimples`.`funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbsimples`.`funcionario` ;

CREATE TABLE IF NOT EXISTS `dbsimples`.`funcionario` (
  `cpf` VARCHAR(20) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `endereco_cep` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`cpf`),
  INDEX `endereco_funcionario_idx` (`endereco_cep` ASC),
  CONSTRAINT `endereco_funcionario`
    FOREIGN KEY (`endereco_cep`)
    REFERENCES `dbsimples`.`endereco` (`cep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsimples`.`fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbsimples`.`fornecedor` ;

CREATE TABLE IF NOT EXISTS `dbsimples`.`fornecedor` (
  `cnpj` VARCHAR(15) NOT NULL,
  `rsocial` VARCHAR(45) NOT NULL,
  `nfantasia` VARCHAR(45) NOT NULL,
  `contato` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `endereco_cep` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`cnpj`),
  INDEX `fornecedor_endereco_idx` (`endereco_cep` ASC),
  CONSTRAINT `fornecedor_endereco`
    FOREIGN KEY (`endereco_cep`)
    REFERENCES `dbsimples`.`endereco` (`cep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsimples`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbsimples`.`usuario` ;

CREATE TABLE IF NOT EXISTS `dbsimples`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `funcionario_cep` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `funcionario_user_idx` (`funcionario_cep` ASC),
  CONSTRAINT `funcionario_user`
    FOREIGN KEY (`funcionario_cep`)
    REFERENCES `dbsimples`.`funcionario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsimples`.`peca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbsimples`.`peca` ;

CREATE TABLE IF NOT EXISTS `dbsimples`.`peca` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `unidade` VARCHAR(45) NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  `fornecedor_cnpj` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `peca_forn_idx` (`fornecedor_cnpj` ASC),
  CONSTRAINT `peca_forn`
    FOREIGN KEY (`fornecedor_cnpj`)
    REFERENCES `dbsimples`.`fornecedor` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsimples`.`servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbsimples`.`servico` ;

CREATE TABLE IF NOT EXISTS `dbsimples`.`servico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `hora` DATETIME NOT NULL,
  `tempo` INT NULL,
  `valor` DOUBLE NULL,
  `cliente_cpf` VARCHAR(15) NOT NULL,
  `funcionario_cpf` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `servico_cliente_idx` (`cliente_cpf` ASC),
  INDEX `servico_func_idx` (`funcionario_cpf` ASC),
  CONSTRAINT `servico_cliente`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `dbsimples`.`cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `servico_func`
    FOREIGN KEY (`funcionario_cpf`)
    REFERENCES `dbsimples`.`funcionario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsimples`.`pecaservico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbsimples`.`pecaservico` ;

CREATE TABLE IF NOT EXISTS `dbsimples`.`pecaservico` (
  `id` INT NOT NULL,
  `peca_id` INT NOT NULL,
  `servico_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `pecaservico_peca_idx` (`peca_id` ASC),
  INDEX `pecaservico_servico_idx` (`servico_id` ASC),
  CONSTRAINT `pecaservico_peca`
    FOREIGN KEY (`peca_id`)
    REFERENCES `dbsimples`.`peca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pecaservico_servico`
    FOREIGN KEY (`servico_id`)
    REFERENCES `dbsimples`.`servico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
